Imports System.IO

Public Class frmReports
    Private Sub TbProductsBindingNavigatorSaveItem_Click(sender As Object, e As EventArgs)
        Me.Validate()
        Me.TbProductsBindingSource.EndEdit()
        Me.TableAdapterManager.UpdateAll(Me.AutosupplyDataSet)

    End Sub

    Private Sub frmReports_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        'TODO: This line of code loads data into the 'AutosupplyDataSet.tbPOS' table. You can move, or remove it, as needed.
        Me.TbPOSTableAdapter.Fill(Me.AutosupplyDataSet.tbPOS)
        'TODO: This line of code loads data into the 'AutosupplyDataSet.tbProducts' table. You can move, or remove it, as needed.
        Me.TbProductsTableAdapter.Fill(Me.AutosupplyDataSet.tbProducts)


        'NOTE: FIRST SET TO FALSE ANG ALLOW USERS TO ADD ROWS SA DATAGRID PROPERTY TO AVOID NULL REFERRENCE

        TbProductsDataGridView.SelectAll()


        'For Daily Inventory Report
        If frmPrint.ComboBox1.SelectedIndex = 0 Then

            Try
                Dim c = Me.TbProductsDataGridView.Rows.Count - 1
                Dim et As Integer = Me.TbProductsDataGridView.Columns.Count - 1

                Dim no As Integer = 0
                Dim i, j As Integer
                RichTextBox1.AppendText("------------------------------------------------------------------------" & vbNewLine)
                RichTextBox1.AppendText("Report Type: Daily Inventory Report" & vbNewLine)
                RichTextBox1.AppendText("Generated By: " & Form1.lblName.Text & vbNewLine)
                RichTextBox1.AppendText("Created: " & Date.Today.ToLongDateString & " " & TimeOfDay.ToLongTimeString & vbNewLine)
                RichTextBox1.AppendText("************************************************************************" & vbNewLine & vbNewLine)

                RichTextBox1.AppendText("1.ProductName| 2.Brand| 3.PartNo.| 4.Quality| 5.Stocks| 6.Supplier| 7.Barcode| 8.Price|" & vbNewLine)
                RichTextBox1.AppendText("Refer to the Values Above for reading the content below......" & vbNewLine & vbNewLine)

                For i = 0 To c Step +1

                    RichTextBox1.Text = RichTextBox1.Text & "************************************************************************"

                    For j = 0 To et Step +1

                        If no < 8 Then
                            no = no + 1
                            RichTextBox1.Text = RichTextBox1.Text & vbNewLine
                            RichTextBox1.Text = RichTextBox1.Text & no & ".|" & TbProductsDataGridView.Rows(i).Cells(j).Value.ToString() & "|  "

                        ElseIf no > 7 Then
                            no = 0
                            no = no + 1
                            RichTextBox1.Text = RichTextBox1.Text & vbNewLine
                            RichTextBox1.Text = RichTextBox1.Text & no & ".|" & TbProductsDataGridView.Rows(i).Cells(j).Value.ToString() & "|  "

                        End If
                        'Below is the original code ,just delete the above lines start from if -elseif-endif if eeror occurs :D Tagay!
                        'RichTextBox1.Text = RichTextBox1.Text & vbNewLine
                        'RichTextBox1.Text = RichTextBox1.Text & "|" & TbProductsDataGridView.Rows(i).Cells(j).Value.ToString() & "|  "

                    Next

                    RichTextBox1.Text = RichTextBox1.Text + vbNewLine
                    RichTextBox1.Text = RichTextBox1.Text + vbNewLine


                Next
                Dim d = Date.Today.ToLongDateString

                Dim log1 As String = System.AppDomain.CurrentDomain.BaseDirectory & "Documents\Reports\Daily Inventory\Daily Inventory " & d & ".rtf"



                If File.Exists(log1) Then

                    'if file exist execute find string

                    'Dim fileLoc = IO.File.ReadAllText(log1)
                    'Dim srch As String = Date.Today.ToLongDateString

                    ''search on our textfile if file we've looking for are exist
                    'If fileLoc.Contains(srch) Then

                    If (MessageBox.Show("There is Already A Report Generated This Day Would You Like To Replace it?", "File Exist", MessageBoxButtons.YesNo, MessageBoxIcon.Question) = DialogResult.Yes) Then
                        frmPrint.ComboBox1.Enabled = False
                        frmPrint.Timer1.Enabled = True
                        frmPrint.pbProcess.Enabled = False
                        frmPrint.pbProcess.BackColor = Color.LightGray
                        frmPrint.pbPrint.Enabled = False
                        frmPrint.pbPrint.BackColor = Color.LightGray

                        File.Delete(log1)
                        File.AppendAllText("Documents\Reports\Daily Inventory\Daily Inventory " & d & ".rtf", RichTextBox1.Text)


                    Else
                        frmPrint.ComboBox1.Enabled = False
                        frmPrint.Timer1.Enabled = True
                        frmPrint.pbProcess.Enabled = False
                        frmPrint.pbProcess.BackColor = Color.LightGray
                        frmPrint.pbPrint.Enabled = False
                        frmPrint.pbPrint.BackColor = Color.LightGray

                        File.AppendAllText("Documents\Reports\Daily Inventory\Daily Inventory " & d & ".rtf", RichTextBox1.Text)

                    End If

                    'Else
                    '    'no action
                    'End If


                Else

                    ' if file is not exist automatic mag write lang sya or append
                    frmPrint.ComboBox1.Enabled = False
                    frmPrint.Timer1.Enabled = True
                    frmPrint.pbProcess.Enabled = False
                    frmPrint.pbProcess.BackColor = Color.LightGray
                    frmPrint.pbPrint.Enabled = False
                    frmPrint.pbPrint.BackColor = Color.LightGray

                    File.AppendAllText("Documents\Reports\Daily Inventory\Daily Inventory " & d & ".rtf", RichTextBox1.Text)


                End If
            Catch ex As Exception
                frmPrint.Timer1.Enabled = False
                MessageBox.Show(ex.Message, "Something Went Wrong", MessageBoxButtons.OK, MessageBoxIcon.Hand)
                frmPrint.ProgressBar1.Value = 100
                frmPrint.lblStat.Text = "Error Occured"
            End Try


            'NOTE: FIRST SET TO FALSE ANG ALLOW USERS TO ADD ROWS SA DATAGRID PROPERTY TO AVOID NULL REFERRENCE

            'For General Inventory Report
        ElseIf frmPrint.comboBox1.SelectedIndex = 1 Then


            Dim d = Date.Today.ToLongDateString

            'check first sa txtfiles if available

            Dim log1 As String = System.AppDomain.CurrentDomain.BaseDirectory & "Documents\Reports\Daily Inventory"
            Dim log2 As String = System.AppDomain.CurrentDomain.BaseDirectory & "Documents\Reports\General Inventory"
            Dim log3 As String = System.AppDomain.CurrentDomain.BaseDirectory & "Documents\Reports\General Inventory\General Inventory.rtf"

            Dim x As New DirectoryInfo(log1)
            Dim y = x.GetFiles



            Dim poop As DirectoryInfo = New DirectoryInfo(log1)
            Dim g As Integer = poop.GetFiles().Count

            Dim cr = Date.Today.ToLongDateString
            Dim ct = TimeOfDay.ToLongTimeString



            Try


                If g > 0 Then



                    For Each z In y

                        If Path.GetExtension(z.FullName).ToLower.Contains("rtf") Then
                            Dim f = IO.File.ReadAllText(z.FullName)

                            frmPrint.ComboBox1.Enabled = False
                            frmPrint.Timer1.Enabled = True
                            frmPrint.pbProcess.Enabled = False
                            frmPrint.pbProcess.BackColor = Color.LightGray
                            frmPrint.pbPrint.Enabled = False
                            frmPrint.pbPrint.BackColor = Color.LightGray



                            If File.Exists(log3) Then
                                File.Delete(log3)

                            Else
                                'no act
                            End If

                            File.AppendAllText(log2 & "\General Inventory.rtf", f)

                            'Write to the end of file
                            File.AppendAllText(log2 & "\General Inventory.rtf", "*************************END OF REPORT**************************" & vbNewLine)
                            File.AppendAllText(log2 & "\General Inventory.rtf", "Report Type: General Report Inventory" & vbNewLine)
                            File.AppendAllText(log2 & "\General Inventory.rtf", "Generated By: " & Form1.lblName.Text & vbNewLine)
                            File.AppendAllText(log2 & "\General Inventory.rtf", "Created: " & cr & " " & ct & vbNewLine)
                            File.AppendAllText(log2 & "\General Inventory.rtf", "*************************************************************************" & vbNewLine & vbNewLine)



                        End If

                    Next

                Else
                    MessageBox.Show("Criteria didn't meet you need to firstly generate daily reports to create a general report", "Can't Perform this task")
                End If

            Catch ex As Exception
                frmPrint.Timer1.Enabled = False
                MessageBox.Show(ex.Message, "Something Went Wrong", MessageBoxButtons.OK, MessageBoxIcon.Hand)
                frmPrint.ProgressBar1.Value = 100
                frmPrint.lblStat.Text = "Error Occured"
            End Try

            'NOTE: FIRST SET TO FALSE ANG ALLOW USERS TO ADD ROWS SA DATAGRID PROPERTY TO AVOID NULL REFERRENCE


            'for Daily Stocks Report
        ElseIf frmPrint.ComboBox1.SelectedIndex = 2 Then
            Try

                Dim c = Me.TbProductsDataGridView1.Rows.Count - 1
                Dim et As Integer = Me.TbProductsDataGridView1.Columns.Count - 1
                Dim no As Integer = 0

                Dim i, j As Integer
                RichTextBox1.AppendText("------------------------------------------------------------------------" & vbNewLine)
                RichTextBox1.AppendText("Report Type: Daily Stocks Report" & vbNewLine)
                RichTextBox1.AppendText("Generated By: " & Form1.lblName.Text & vbNewLine)
                RichTextBox1.AppendText("Created: " & Date.Today.ToLongDateString & " " & TimeOfDay.ToLongTimeString & vbNewLine)
                RichTextBox1.AppendText("************************************************************************" & vbNewLine & vbNewLine)

                RichTextBox1.AppendText("1.ProductName| 2.Stocks| 3.Supplier| 4.Barcode|" & vbNewLine)
                RichTextBox1.AppendText("Refer to the Values Above for reading the content below......" & vbNewLine & vbNewLine)

                For i = 0 To c Step +1

                    RichTextBox1.Text = RichTextBox1.Text & "************************************************************************"

                    For j = 0 To et Step +1
                        If no < 4 Then
                            no = no + 1

                            RichTextBox1.Text = RichTextBox1.Text & vbNewLine
                            RichTextBox1.Text = RichTextBox1.Text & no & ".|" & TbProductsDataGridView1.Rows(i).Cells(j).Value.ToString() & "|  "

                        ElseIf no > 3 Then
                            no = 0
                            no = no + 1

                            RichTextBox1.Text = RichTextBox1.Text & vbNewLine
                            RichTextBox1.Text = RichTextBox1.Text & no & ".|" & TbProductsDataGridView1.Rows(i).Cells(j).Value.ToString() & "|  "

                        End If

                    Next

                    RichTextBox1.Text = RichTextBox1.Text + vbNewLine
                    RichTextBox1.Text = RichTextBox1.Text + vbNewLine


                Next

                Dim d = Date.Today.ToLongDateString

                Dim log1 As String = System.AppDomain.CurrentDomain.BaseDirectory & "Documents\Reports\Daily Stocks\Daily Stocks " & d & ".rtf"



                If File.Exists(log1) Then
                    'if file exist execute find string

                    Dim fileLoc = IO.File.ReadAllText(log1)
                    Dim srch As String = Date.Today.ToLongDateString

                    'search on our textfile if file we've looking for are exist
                    If fileLoc.Contains(srch) Then
                        If (MessageBox.Show("There is Already A Report Generated This Day Would You Like To Replace it?", "File Exist", MessageBoxButtons.YesNo, MessageBoxIcon.Question) = DialogResult.Yes) Then
                            frmPrint.ComboBox1.Enabled = False
                            frmPrint.Timer1.Enabled = True
                            frmPrint.pbProcess.Enabled = False
                            frmPrint.pbProcess.BackColor = Color.LightGray
                            frmPrint.pbPrint.Enabled = False
                            frmPrint.pbPrint.BackColor = Color.LightGray

                            File.Delete(log1)
                            File.AppendAllText("Documents\Reports\Daily Stocks\Daily Stocks " & d & ".rtf", RichTextBox1.Text)


                        Else
                            frmPrint.ComboBox1.Enabled = False
                            frmPrint.Timer1.Enabled = True
                            frmPrint.pbProcess.Enabled = False
                            frmPrint.pbProcess.BackColor = Color.LightGray
                            frmPrint.pbPrint.Enabled = False
                            frmPrint.pbPrint.BackColor = Color.LightGray

                            File.AppendAllText("Documents\Reports\Daily Stocks\Daily Stocks " & d & ".rtf", RichTextBox1.Text)

                        End If

                    Else
                        'no action
                    End If



                Else

                    ' if file is not exist automatic mag write lang sya or append
                    frmPrint.ComboBox1.Enabled = False
                    frmPrint.Timer1.Enabled = True
                    frmPrint.pbProcess.Enabled = False
                    frmPrint.pbProcess.BackColor = Color.LightGray
                    frmPrint.pbPrint.Enabled = False
                    frmPrint.pbPrint.BackColor = Color.LightGray


                    File.AppendAllText("Documents\Reports\Daily Stocks\Daily Stocks " & d & ".rtf", RichTextBox1.Text)



                End If

            Catch o As Exception
                frmPrint.Timer1.Enabled = False
                MessageBox.Show(o.Message, "Something Went Wrong", MessageBoxButtons.OK, MessageBoxIcon.Hand)
                frmPrint.ProgressBar1.Value = 100
                frmPrint.lblStat.Text = "Error Occured"
            End Try


            'For Daily Purchase
        ElseIf frmPrint.comboBox1.SelectedIndex = 3 Then

            Try
                TbPOSBindingSource.Filter = "(CONVERT(TransactionDate, 'System.String')LIKE'" & Date.Today.ToLongDateString & "')"
                If TbPOSBindingSource.Count = 0 Then
                    MessageBox.Show("No Transaction made this day", "Invalid", MessageBoxButtons.OK)

                Else
                    Dim c = Me.TbPOSDataGridView.Rows.Count - 1
                    Dim et As Integer = Me.TbPOSDataGridView.Columns.Count - 1
                    Dim no As Integer = 0
                    Dim i, j As Integer

                    RichTextBox1.AppendText("------------------------------------------------------------------------" & vbNewLine)
                    RichTextBox1.AppendText("Report Type: Daily Purchase Report" & vbNewLine)
                    RichTextBox1.AppendText("Generated By: " & Form1.lblName.Text & vbNewLine)
                    RichTextBox1.AppendText("Created: " & Date.Today.ToLongDateString & " " & TimeOfDay.ToLongTimeString & vbNewLine)
                    RichTextBox1.AppendText("************************************************************************" & vbNewLine & vbNewLine)
                    RichTextBox1.AppendText("1.Transaction Date| 2.Transaction Time| 3.Breakdowns| 4.Signed|" & vbNewLine)
                    RichTextBox1.AppendText("Refer to the Values Above for reading the content below......" & vbNewLine & vbNewLine)
                    For i = 0 To c Step +1

                        RichTextBox1.Text = RichTextBox1.Text & "************************************************************************"

                        For j = 0 To et Step +1
                            If no < 4 Then
                                no = no + 1

                                RichTextBox1.Text = RichTextBox1.Text & vbNewLine
                                RichTextBox1.Text = RichTextBox1.Text & no & ".|" & TbPOSDataGridView.Rows(i).Cells(j).Value.ToString() & "|  "

                            ElseIf no > 3 Then
                                no = 0
                                no = no + 1

                                RichTextBox1.Text = RichTextBox1.Text & vbNewLine
                                RichTextBox1.Text = RichTextBox1.Text & no & ".|" & TbPOSDataGridView.Rows(i).Cells(j).Value.ToString() & "|  "

                            End If

                        Next

                        RichTextBox1.Text = RichTextBox1.Text + vbNewLine
                        RichTextBox1.Text = RichTextBox1.Text + vbNewLine


                    Next

                    Dim d = Date.Today.ToLongDateString

                    Dim log1 As String = System.AppDomain.CurrentDomain.BaseDirectory & "Documents\Reports\Daily Purchase\Daily Purchase" & d & ".rtf"



                    If File.Exists(log1) Then
                        'if file exist execute find string

                        Dim fileLoc = IO.File.ReadAllText(log1)
                        Dim srch As String = Date.Today.ToLongDateString

                        'search on our textfile if file we've looking for are exist
                        If fileLoc.Contains(srch) Then
                            If (MessageBox.Show("There is Already A Report Generated This Day Would You Like To Replace it?", "File Exist", MessageBoxButtons.YesNo, MessageBoxIcon.Question) = DialogResult.Yes) Then
                                frmPrint.ComboBox1.Enabled = False
                                frmPrint.Timer1.Enabled = True
                                frmPrint.pbProcess.Enabled = False
                                frmPrint.pbProcess.BackColor = Color.LightGray
                                frmPrint.pbPrint.Enabled = False
                                frmPrint.pbPrint.BackColor = Color.LightGray

                                File.Delete(log1)
                                File.AppendAllText("Documents\Reports\Daily Purchase\Daily Purchase" & d & ".rtf", RichTextBox1.Text)


                            Else
                                frmPrint.ComboBox1.Enabled = False
                                frmPrint.Timer1.Enabled = True
                                frmPrint.pbProcess.Enabled = False
                                frmPrint.pbProcess.BackColor = Color.LightGray
                                frmPrint.pbPrint.Enabled = False
                                frmPrint.pbPrint.BackColor = Color.LightGray

                                File.AppendAllText("Documents\Reports\Daily Purchase\Daily Purchase" & d & ".rtf", RichTextBox1.Text)

                            End If

                        Else

                        End If



                    Else

                        ' if file is not exist automatic mag write lang sya or append
                        frmPrint.ComboBox1.Enabled = False
                        frmPrint.Timer1.Enabled = True
                        frmPrint.pbProcess.Enabled = False
                        frmPrint.pbProcess.BackColor = Color.LightGray
                        frmPrint.pbPrint.Enabled = False
                        frmPrint.pbPrint.BackColor = Color.LightGray


                        File.AppendAllText("Documents\Reports\Daily Purchase\Daily Purchase" & d & ".rtf", RichTextBox1.Text)



                    End If
                End If


            Catch ex As Exception

            End Try


            'NOTE: FIRST SET TO FALSE ANG ALLOW USERS TO ADD ROWS SA DATAGRID PROPERTY TO AVOID NULL REFERRENCE

            'For General Purchase Report
        ElseIf frmPrint.ComboBox1.SelectedIndex = 4 Then


            Dim d = Date.Today.ToLongDateString

            'check first sa txtfiles if available

            Dim log1 As String = System.AppDomain.CurrentDomain.BaseDirectory & "Documents\Reports\Daily Purchase"
            Dim log2 As String = System.AppDomain.CurrentDomain.BaseDirectory & "Documents\Reports\General Purchase"
            Dim log3 As String = System.AppDomain.CurrentDomain.BaseDirectory & "Documents\Reports\General Purchase\General Purchase.rtf"

            Dim x As New DirectoryInfo(log1)
            Dim y = x.GetFiles



            Dim poop As DirectoryInfo = New DirectoryInfo(log1)
            Dim g As Integer = poop.GetFiles().Count

            Dim cr = Date.Today.ToLongDateString
            Dim ct = TimeOfDay.ToLongTimeString



            Try


                If g > 0 Then



                    For Each z In y

                        If Path.GetExtension(z.FullName).ToLower.Contains("rtf") Then
                            Dim f = IO.File.ReadAllText(z.FullName)

                            frmPrint.ComboBox1.Enabled = False
                            frmPrint.Timer1.Enabled = True
                            frmPrint.pbProcess.Enabled = False
                            frmPrint.pbProcess.BackColor = Color.LightGray
                            frmPrint.pbPrint.Enabled = False
                            frmPrint.pbPrint.BackColor = Color.LightGray



                            If File.Exists(log3) Then
                                File.Delete(log3)

                            Else
                                'no act
                            End If

                            File.AppendAllText(log2 & "\General Purchase.rtf", f)

                            'Write to the end of file
                            File.AppendAllText(log2 & "\General Purchase.rtf", "*************************END OF REPORT**************************" & vbNewLine)
                            File.AppendAllText(log2 & "\General Purchase.rtf", "Report Type: General Purchase Report" & vbNewLine)
                            File.AppendAllText(log2 & "\General Purchase.rtf", "Generated By: " & Form1.lblName.Text & vbNewLine)
                            File.AppendAllText(log2 & "\General Purchase.rtf", "Created: " & cr & " " & ct & vbNewLine)
                            File.AppendAllText(log2 & "\General Purchase.rtf", "*************************************************************************" & vbNewLine & vbNewLine)

                        End If

                    Next

                Else
                    MessageBox.Show("Criteria didn't meet you need to firstly generate daily Purchase to create a general report", "Can't Perform this task")
                End If

            Catch ex As Exception
                frmPrint.Timer1.Enabled = False
                MessageBox.Show(ex.Message, "Something Went Wrong", MessageBoxButtons.OK, MessageBoxIcon.Hand)
                frmPrint.ProgressBar1.Value = 100
                frmPrint.lblStat.Text = "Error Occured"
            End Try



        End If


        Me.Close()

    End Sub


End Class